<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/1999/REC-html401-19991224/loose.dtd">
<html>
<head>
	<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">


	<title>Zapatec DHTML Tabs Widget - Closable Demo</title>

	<!-- Common JS files -->
	<script type='text/javascript' src='../../utils/zapatec.js'></script>

	<!-- Custom includes -->	
	<script type="text/javascript" src="../src/zptabs.js"></script>

	<!-- ALL demos need these css -->
	<link href="../../website/css/zpcal.css" rel="stylesheet" type="text/css">
	<link href="../../website/css/template.css" rel="stylesheet" type="text/css">
	


</head>
<body>	

<div id="tabBar" style="width: 99%"></div>

<div id="tabs" style="height: 99%">
  <div id="home">
    <label accesskey="h" title="Home"><u>H</u>ome</label>
  </div>
  <div id="inbox">
    <label accesskey="i" title="Inbox"  ><u>I</u>nbox</label>
    Inbox Tab
  </div>
  <div id="spam">
    <label accesskey="s" title="Spam"  ><u>S</u>pam</label>
    Spam Tab
  </div>
</div>



<script type="text/javascript">

var objTabs = new Zapatec.Tabs({
  // ID of Top bar to show the Tabs: Game, Photo, Music, Chat
  tabBar: 'tabBar',
  /*
  ID to get the LABEL contents to create the tabBar tabs
  Also, each DIV in this ID will contain the contents for each tab
  */
  tabs: 'tabs',
  // Theme to use for the tabs
  theme: 'rounded',
  themePath: '../themes/',
  closeAction: 'hide'
});



</script>


	
		</div>
</body>
</html>
