<?php
include_once('../app/modelo/clase_mysqli.inc.php');
$con = new DB_mysqli();
$con->select_db($con->temporal);
$catalogo = $con->catalogo;
$idproveedor = $argv[2];
$fecha = $argv[1];
$fechageneracion = date("Y-m-d");

$fecha1 = rand(1,20);
echo $idproveedor;
echo $fecha;

$tabla = 'tmp_carga_cde'.$fecha1;



$sql_tmp = "CREATE  TABLE $tabla (                                            
                 `ID` int(10) unsigned NOT NULL auto_increment,                          
                 `IDPROVEEDOR` int(10) NOT NULL,                                         
                 `IDASISTENCIA` int(10) NOT NULL,                                        
                 `IDSERVICIO` int(4) NOT NULL,                                           
                 `IMPORTANCIA` char(20) NOT NULL,                                        
                 `LOCALFORANEO` char(2) NOT NULL,                                        
                 `DEFLEVELOCAL` int(4) NOT NULL,                                         
                 `DEFGRAVELOCAL` int(4) NOT NULL,                                        
                 `DEFLEVEFORANEO` int(4) NOT NULL,                                       
                 `DEFGRAVEFORANEO` int(4) NOT NULL,                                      
                 `FECHAHORAASISTENCIA` datetime NOT NULL,                                
                 PRIMARY KEY  (`ID`,`IDPROVEEDOR`,`IDASISTENCIA`,`FECHAHORAASISTENCIA`)  
               ) ";
//echo $sql_tmp;
$exec_sql_tmp = $con->query($sql_tmp);
//OBTENEMOS PARAMETROS
$sql_parametro="select IDPARAMETRO,DATODEFAULT FROM $catalogo.catalogo_parametro WHERE IDPARAMETRO IN('LEVE_CDE','GRAVE_CDE','MAXIMO_SERVICIO')";
$exec_parametro = $con->query($sql_parametro);
while($rset_parametro=$exec_parametro->fetch_object())
{
	$XIDPARAMETRO = $rset_parametro->IDPARAMETRO;
	switch($XIDPARAMETRO){
	case 'LEVE_CDE': $PONLEVE = $rset_parametro->DATODEFAULT;break;
	case 'GRAVE_CDE': $PONGRAVE = $rset_parametro->DATODEFAULT;break;
	case 'MAXIMO_SERVICIO': $var_nreg = $rset_parametro->DATODEFAULT;break;
	}
}
//echo $PONLEVE;
//echo $PONGRAVE;
//$sql_del_tmp="delete from $tabla";
//$exec_del_tmp = $con->query($sql_del_tmp);

if($idproveedor==0){
$sql_prov =  "select IDPROVEEDOR,NOMBRECOMERCIAL,NOMBREFISCAL from $catalogo.catalogo_proveedor";
}
else
{
$sql_prov =  "select IDPROVEEDOR,NOMBRECOMERCIAL,NOMBREFISCAL from $catalogo.catalogo_proveedor where IDPROVEEDOR=$idproveedor";
}
//echo $sql_prov;
$exec_prov = $con->query($sql_prov);

while($rset_prov=$exec_prov->fetch_object())
{
	$XIDPROVEEDOR =  $rset_prov->IDPROVEEDOR;
//	echo $XNOMBRECOMERCIAL.' ';
	/*
	$sql_asis_prov = "insert into $tabla(IDPROVEEDOR,IDASISTENCIA,FECHAHORAASISTENCIA,LOCALFORANEO,IDSERVICIO)
	 select $XIDPROVEEDOR,IF(AP.IDASISTENCIA ='','',AP.IDASISTENCIA),AU.FECHAHORA,
	IF(AP.LOCALFORANEO ='','',AP.LOCALFORANEO),CASE(A.IDFAMILIA)
	WHEN 1 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_vehicular AV ON S.IDSERVICIO = AV.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA) 
	WHEN 3 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_hogar AH ON S.IDSERVICIO = AH.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA) 
	WHEN 4 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_medica AM ON S.IDSERVICIO = AM.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)
	WHEN 5 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_pc APC ON S.IDSERVICIO = APC.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA) 
	WHEN 6 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_viaje AVJ ON S.IDSERVICIO = AVJ.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)
	WHEN 7 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_legal AL ON S.IDSERVICIO = AL.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)  
	WHEN 8 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_mascota AMS ON S.IDSERVICIO = AMS.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)  
	WHEN 9 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_siniestro ASN ON S.IDSERVICIO = ASN.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)
	WHEN 10 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_escolar AE ON S.IDSERVICIO = AE.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)    
	WHEN 2 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_referencias AR ON S.IDSERVICIO = AR.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)    
	END as SERVICIO
	 FROM asistencia_asig_proveedor AP INNER JOIN asistencia_usuario AU 
	ON AP.IDASISTENCIA = AU.IDASISTENCIA INNER JOIN asistencia A
	ON AP.IDASISTENCIA = A.IDASISTENCIA WHERE AP.IDPROVEEDOR = ".$XIDPROVEEDOR."
	union 
	select $XIDPROVEEDOR,'','','','' FROM $catalogo.catalogo_proveedor
	 WHERE $XIDPROVEEDOR NOT IN (SELECT IDPROVEEDOR FROM asistencia_asig_proveedor)  ORDER BY 3 DESC LIMIT $var_nreg";
*/
//	
	$sql_asis_prov = "insert into $tabla(IDPROVEEDOR,IDASISTENCIA,FECHAHORAASISTENCIA,LOCALFORANEO,IDSERVICIO)
	 select $XIDPROVEEDOR,IF(AP.IDASISTENCIA ='','',AP.IDASISTENCIA),AU.FECHAHORA,
	IF(AP.LOCALFORANEO ='','',AP.LOCALFORANEO),A.IDSERVICIO SERVICIO
	 FROM asistencia_asig_proveedor AP INNER JOIN asistencia_usuario AU 
	ON AP.IDASISTENCIA = AU.IDASISTENCIA INNER JOIN asistencia A
	ON AP.IDASISTENCIA = A.IDASISTENCIA WHERE AP.IDPROVEEDOR = ".$XIDPROVEEDOR."
	GROUP BY AP.IDASISTENCIA
	union 
	select $XIDPROVEEDOR,'','','','' FROM $catalogo.catalogo_proveedor
	 WHERE $XIDPROVEEDOR NOT IN (SELECT IDPROVEEDOR FROM asistencia_asig_proveedor)  ORDER BY 3 DESC LIMIT $var_nreg";


echo $sql_asis_prov;

	$exec_asis_prov = $con->query($sql_asis_prov);

	$sql_consulta_tmp="SELECT IDPROVEEDOR,IDASISTENCIA FROM $tabla WHERE IDPROVEEDOR=$XIDPROVEEDOR";
//	echo $sql_consulta_tmp;
	$exec_consulta_tmp=$con->query($sql_consulta_tmp);
	while($rset_consulta_tmp = $exec_consulta_tmp->fetch_object())
	{
		$XTMPIDPROVEEDOR=$rset_consulta_tmp->IDPROVEEDOR;
		$XTMPIDASISTENCIA=$rset_consulta_tmp->IDASISTENCIA;


$sql_asis_def="select 
COUNT(CASE(IF(D.IMPORTANCIA='LEVE' AND AP.LOCALFORANEO = 'L','TRUE','FALSE')) WHEN 'TRUE' THEN ED.CVEDEFICIENCIA END) LOCALLEVE,
COUNT(CASE(IF(D.IMPORTANCIA='GRAVE' AND AP.LOCALFORANEO = 'L','TRUE','FALSE')) WHEN 'TRUE' THEN ED.CVEDEFICIENCIA END) LOCALGRAVE,
COUNT(CASE(IF(D.IMPORTANCIA='LEVE' AND AP.LOCALFORANEO = 'F','TRUE','FALSE')) WHEN 'TRUE' THEN ED.CVEDEFICIENCIA END) FORANEOLEVE,
COUNT(CASE(IF(D.IMPORTANCIA='GRAVE' AND AP.LOCALFORANEO = 'F','TRUE','FALSE')) WHEN 'TRUE' THEN ED.CVEDEFICIENCIA END) FORANEOGRAVE
 FROM expediente_deficiencia ED
 INNER JOIN $catalogo.catalogo_deficiencia D ON ED.CVEDEFICIENCIA = D.CVEDEFICIENCIA
INNER JOIN asistencia A ON ED.IDASISTENCIA = A.IDASISTENCIA 
INNER JOIN asistencia_asig_proveedor AP ON A.IDASISTENCIA= AP.IDASISTENCIA
where ED.IDASISTENCIA = ".$XTMPIDASISTENCIA." AND ORIGEN='EXTERNO' AND ED.IDPROVEEDOR=".$XTMPIDPROVEEDOR." GROUP BY AP.LOCALFORANEO";
		//echo $sql_asis_def;
		$exec_asis_def = $con->query($sql_asis_def);
		if($rset_asis_def=$exec_asis_def->fetch_object())
		{
			$XDEFLEVELOCAL= $rset_asis_def->LOCALLEVE;
			$XDEFGRAVELOCAL = $rset_asis_def->LOCALGRAVE;
			$XDEFLEVEFORANEO= $rset_asis_def->FORANEOLEVE;
			$XDEFGRAVEFORANEO = $rset_asis_def->FORANEOGRAVE;
			$sql_update_def = "UPDATE $tabla SET DEFLEVELOCAL=$XDEFLEVELOCAL,DEFGRAVELOCAL=$XDEFGRAVELOCAL,
			DEFLEVEFORANEO=$XDEFLEVEFORANEO,DEFGRAVEFORANEO=$XDEFGRAVEFORANEO WHERE IDPROVEEDOR = $XTMPIDPROVEEDOR
			 AND IDASISTENCIA = $XTMPIDASISTENCIA";
			//echo $sql_update_def;
			$exec_update_def = $con->query($sql_update_def);
			
		}		
		
		
	}

}

if($idproveedor==0){
$sql_servicio = "SELECT * FROM $catalogo.catalogo_servicio";
$exec_servicio = $con->query($sql_servicio);

while($rset_servicio = $exec_servicio->fetch_object())
{

$XIDSERVICIO = $rset_servicio->IDSERVICIO;

$sql_cde = " INSERT INTO proceso_carga_cde(IDSERVICIO,TOTALEVALUADO,IDPROVEEDOR,LEVELOCAL,LEVEFORANEO,GRAVELOCAL,GRAVEFORANEO,DEFLEVES,DEFGRAVE,PORLEVE,PORGRAVE,CDE,FECHAHORA)
SELECT IDSERVICIO,COUNT(IDASISTENCIA) TOTALEVALUADOS,P.IDPROVEEDOR,
(SELECT COUNT(DEFLEVELOCAL) FROM $tabla WHERE DEFLEVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) LEVELOCAL,
(SELECT COUNT(DEFLEVEFORANEO) FROM $tabla WHERE DEFLEVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) LEVEFORANEO,
(SELECT COUNT(DEFGRAVELOCAL) FROM $tabla WHERE DEFGRAVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) GRAVELOCAL,
(SELECT COUNT(DEFGRAVEFORANEO) FROM $tabla WHERE DEFGRAVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) GRAVEFORANEO,

(SELECT COUNT(DEFLEVELOCAL) FROM $tabla WHERE DEFLEVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR)+
(SELECT COUNT(DEFLEVEFORANEO) FROM $tabla WHERE DEFLEVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) 
 AS TOTALLEVES,
(SELECT COUNT(DEFGRAVELOCAL) FROM $tabla WHERE DEFGRAVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR)+
(SELECT COUNT(DEFGRAVEFORANEO) FROM $tabla WHERE DEFGRAVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR)
 AS TOTALGRAVE,
(IF(COUNT(IDASISTENCIA)=0,0,((SELECT COUNT(DEFLEVELOCAL) FROM $tabla WHERE DEFLEVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR)+
(SELECT COUNT(DEFLEVEFORANEO) FROM $tabla WHERE DEFLEVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR)) / COUNT(IDASISTENCIA)))*100 AS PORLEVE,
(IF(COUNT(IDASISTENCIA)=0,0,((SELECT COUNT(DEFGRAVELOCAL) FROM $tabla WHERE DEFGRAVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR)+
(SELECT COUNT(DEFGRAVEFORANEO) FROM $tabla WHERE DEFGRAVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR))/ COUNT(IDASISTENCIA)))*100 AS PORGRAVE,

IF((100-((((IF(COUNT(IDASISTENCIA)=0,0,((SELECT COUNT(DEFLEVELOCAL) FROM $tabla WHERE DEFLEVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR)+
(SELECT COUNT(DEFLEVEFORANEO) FROM $tabla WHERE DEFLEVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR)) / COUNT(IDASISTENCIA)))*100)*$PONLEVE)+
(((IF(COUNT(IDASISTENCIA)=0,0,((SELECT COUNT(DEFGRAVELOCAL) FROM $tabla WHERE DEFGRAVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR)+
(SELECT COUNT(DEFGRAVEFORANEO) FROM $tabla WHERE DEFGRAVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR))/ COUNT(IDASISTENCIA)))*100) *$PONGRAVE)))>0,
(100-((((IF(COUNT(IDASISTENCIA)=0,0,((SELECT COUNT(DEFLEVELOCAL) FROM $tabla WHERE DEFLEVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR)+
(SELECT COUNT(DEFLEVEFORANEO) FROM $tabla WHERE DEFLEVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR)) / COUNT(IDASISTENCIA)))*100)*$PONLEVE)+
(((IF(COUNT(IDASISTENCIA)=0,0,((SELECT COUNT(DEFGRAVELOCAL) FROM $tabla WHERE DEFGRAVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR)+
(SELECT COUNT(DEFGRAVEFORANEO) FROM $tabla WHERE DEFGRAVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR))/ COUNT(IDASISTENCIA)))*100) *$PONGRAVE))),0)
 AS CDE,'$fecha'
FROM $tabla P
WHERE P.IDSERVICIO = '$XIDSERVICIO'
GROUP BY P.IDPROVEEDOR";
//echo $sql_cde;
$exec_cde = $con->query($sql_cde);
}

$sql_insert_prov = "insert into proceso_carga_cde(IDPROVEEDOR,IDSERVICIO,CDE,FECHAHORA) 
select PS.IDPROVEEDOR,PS.IDSERVICIO,100,'$fecha' FROM $catalogo.catalogo_proveedor_servicio PS where PS.IDPROVEEDOR 
NOT IN (SELECT DISTINCT IDPROVEEDOR FROM proceso_carga_cde WHERE FECHAHORA='$fecha' AND IDSERVICIO = PS.IDSERVICIO)";
//echo $sql_insert_prov;
$exec_insert_prov = $con->query($sql_insert_prov);
}
else
{
$sql_servicio = "SELECT * FROM $catalogo.catalogo_servicio";
$exec_servicio = $con->query($sql_servicio);

while($rset_servicio = $exec_servicio->fetch_object())
{

$XIDSERVICIO = $rset_servicio->IDSERVICIO;

$sql_consulta_cde="SELECT IDSERVICIO,COUNT(IDASISTENCIA) TOTALEVALUADOS,P.IDPROVEEDOR,
(SELECT COUNT(DEFLEVELOCAL) FROM $tabla WHERE DEFLEVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) LEVELOCAL,
(SELECT COUNT(DEFLEVEFORANEO) FROM $tabla WHERE DEFLEVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) LEVEFORANEO,
(SELECT COUNT(DEFGRAVELOCAL) FROM $tabla WHERE DEFGRAVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) GRAVELOCAL,
(SELECT COUNT(DEFGRAVEFORANEO) FROM $tabla WHERE DEFGRAVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) GRAVEFORANEO,
IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM $tabla
WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0) AS TOTALLEVE,
IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM $temporal.$tabla
WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0) AS TOTALGRAVE,
(IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM $tabla
WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100 AS PORLEVE,
(IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM $tabla
WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100 AS PORGRAVE,
IF((100-(((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM $tabla
WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*$PONLEVE)+
((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM $tabla
WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*$PONGRAVE)))>0,
(100-(((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM $tabla
WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*$PONLEVE)
+((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM $tabla
WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*$PONGRAVE))),0) AS CDE,'$fechageneracion'
FROM $tabla P
WHERE P.IDSERVICIO = '$XIDSERVICIO' and P.IDPROVEEDOR = '$idproveedor'
GROUP BY P.IDPROVEEDOR";

//echo $sql_consulta_cde;
$exec_consulta_cde = $con->query($sql_consulta_cde);

	while($rset_consulta_cde=$exec_consulta_cde->fetch_object()){
		$XIDSERVICIO = $rset_consulta_cde->IDSERVICIO;
		$XTOTALEVALUADOS = $rset_consulta_cde->TOTALEVALUADOS;
		$XIDPROVEEDOR = $rset_consulta_cde->IDPROVEEDOR;
		$XLEVELOCAL = $rset_consulta_cde->LEVELOCAL;
		$XLEVEFORANEO = $rset_consulta_cde->LEVEFORANEO;
		$XGRAVELOCAL = $rset_consulta_cde->GRAVELOCAL;
		$XGRAVEFORANEO = $rset_consulta_cde->GRAVEFORANEO;
		$XTOTALLEVE = $rset_consulta_cde->TOTALLEVE;
		$XTOTALGRAVE = $rset_consulta_cde->TOTALGRAVE;
		$XPORLEVE = $rset_consulta_cde->PORLEVE;
		$XPORGRAVE = $rset_consulta_cde->PORGRAVE;
		$XCDE = $rset_consulta_cde->CDE;

		$sql_cde = "UPDATE proceso_carga_cde SET TOTALEVALUADOS = $XTOTALEVALUADOS,LEVELOCAL=$XLEVELOCAL,LEVEFORANEO=$XLEVEFORANEO,GRAVELOCAL=$XGRAVELOCAL,
	GRAVEFORANEO=$XGRAVEFORANEO,TOTALLEVE=$XTOTALLEVE,TOTALGRAVE=$XTOTALGRAVE,PORLEVE=$XPORLEVE=PORGRAVE=$XPORGRAVE,CDE=$XCDE WHERE IDSERVICIO=$XIDSERVICIO AND   IDPROVEEDOR=$idproveedor AND FECHAHORA = $fecha";
		$exec_cde = $con->query($sql_cde);

		

	}
   }
}
//actualizamos el cde del proveedor por servicio
$sql_consulta_final_cde = "SELECT IDPROVEEDOR,IDSERVICIO,CDE FROM proceso_carga_cde WHERE FECHAHORA = $fecha";
$exec_consulta_final_cde = $con->query($sql_consulta_final_cde);
while($rset_consulta_final_cde = $exec_consulta_final_cde->fetch_object()){
	$finalproveedor = $rset_consulta_final_cde->IDPROVEEDOR;
	$finalservicio = $rset_consulta_final_cde->IDSERVICIO;
	$finalcde = $rset_consulta_final_cde->CDE;
		$sql_actualiza_cde_servicio="UPDATE $catalogo.catalogo_proveedor_servicio SET CDE = $finalcde WHERE
		IDSERVICIO=$finalservicio AND   IDPROVEEDOR=$finalproveedor";
		//echo $sql_actualiza_cde_servicio;
		$exec_actualiza_cde_servicio = $con->query($sql_actualiza_cde_servicio);


}
//$sql_drop_tmp = "drop table $temporal.$tabla";
//$exec_drop_tmp = $con->query($sql_drop_tmp);
?>
