<?php
include_once('app/modelo/clase_mysqli.inc.php');
$con = new DB_mysqli();
$con->select_db($con->temporal);
$catalogo = $con->catalogo;

$idproveedor = $argv[2];
$fecha = $argv[1];
$fechageneracion = date("Y-m-d");



$sql_tmp = "CREATE  TABLE $tabla (                                            
                 `ID` int(10) unsigned NOT NULL auto_increment,                          
                 `IDPROVEEDOR` int(10) NOT NULL,                                         
                 `IDASISTENCIA` int(10) NOT NULL,                                        
                 `IDSERVICIO` int(4) NOT NULL,                                           
                 `IMPORTANCIA` char(20) NOT NULL,                                        
                 `LOCALFORANEO` char(2) NOT NULL,                                        
                 `DEFLEVELOCAL` int(4) NOT NULL,                                         
                 `DEFGRAVELOCAL` int(4) NOT NULL,                                        
                 `DEFLEVEFORANEO` int(4) NOT NULL,                                       
                 `DEFGRAVEFORANEO` int(4) NOT NULL,                                      
                 `FECHAHORAASISTENCIA` datetime NOT NULL,                                
                 PRIMARY KEY  (`ID`,`IDPROVEEDOR`,`IDASISTENCIA`,`FECHAHORAASISTENCIA`)  
               ) ";
//echo $sql_tmp;
$exec_sql_tmp = $con->query($sql_tmp);

$XANIO=date("Y");
$XMES=date("m");

if($XMES=='01'){
	$XMES=12;
	$XANIO = $XANIO-1;
}
else{
	$XMES = $XMES-1;

}
if($XMES <10){
$XMES = '0'.$XMES;
}

$XFECHAINI=$XANIO.'-'.$XMES.'-'.'01 00:00:00';
$XFECHAFIN=$XANIO.'-'.$XMES.'-'.'31 23:59:59';

$sql_parametro="select IDPARAMETRO,DATODEFAULT FROM $catalogo.catalogo_parametro WHERE IDPARAMETRO IN('LEVE_CDE','GRAVE_CDE','MAXIMO_SERVICIO')";
$exec_parametro = $con-query($sql_parametro);
while($rset_parametro=$exec_parametro->fetch_object())
{
	$XIDPARAMETRO = $rset_parametro->IDPARAMETRO;
	switch($XIDPARAMETRO){
	case 'LEVE_CDE': $PONLEVE = $rset_parametro->DATODEFAULT;break;
	case 'GRAVE_CDE': $PONGRAVE = $rset_parametro->DATODEFAULT;break;
	case 'MAXIMO_SERVICIO': $var_nreg = $rset_parametro->DATODEFAULT;break;
	}
}

$sql_del_tmp="delete from tmp_carga_cde";
$exec_del_tmp = $con->query($sql_del_tmp);

if($idproveedor==0){
$sql_prov =  "select IDPROVEEDOR,NOMBRECOMERCIAL,NOMBREFISCAL from $catalogo.catalogo_proveedor";
}
else
{
$sql_prov =  "select IDPROVEEDOR,NOMBRECOMERCIAL,NOMBREFISCAL from $catalogo.catalogo_proveedor where IDPROVEEDOR=$idproveedor";
}

$exec_prov=$con->query($sql_prov);

while($rset_prov=$exec_prov->fetch_object())
{
	$XIDPROVEEDOR =  $rset_prov->IDPROVEEDOR;
//	echo $XNOMBRECOMERCIAL.' ';
	
	$sql_asis_prov = "insert into tmp_carga_cde(IDPROVEEDOR,IDASISTENCIA,FECHAHORAASISTENCIA,LOCALFORANEO,IDSERVICIO)
	 select $XIDPROVEEDOR,IF(AP.IDASISTENCIA ='','',AP.IDASISTENCIA),AU.FECHAHORA,
	IF(A.LOCALFORANEO ='','',A.LOCALFORANEO),CASE(A.IDFAMILIA)
	WHEN 1 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_vehicular AV ON S.IDSERVICIO = AV.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA) 
	WHEN 3 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_hogar AH ON S.IDSERVICIO = AH.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA) 
	WHEN 4 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_medica AM ON S.IDSERVICIO = AM.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)
	WHEN 5 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_pc APC ON S.IDSERVICIO = APC.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA) 
	WHEN 6 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_viaje AVJ ON S.IDSERVICIO = AVJ.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)
	WHEN 7 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_legal AL ON S.IDSERVICIO = AL.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)  
	WHEN 8 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_mascota AMS ON S.IDSERVICIO = AMS.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)  
	WHEN 9 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_siniestro ASN ON S.IDSERVICIO = ASN.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)
	WHEN 10 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_escolar AE ON S.IDSERVICIO = AE.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)    
	WHEN 2 THEN (SELECT S.IDSERVICIO FROM $catalogo.catalogo_servicio S INNER JOIN asistencia_referencias AR ON S.IDSERVICIO = AR.IDSERVICIO  WHERE IDASISTENCIA = A.IDASISTENCIA)    
	END as SERVICIO
	 FROM asistencia_asig_proveedor AP INNER JOIN asistencia_usuario AU 
	ON AP.IDASISTENCIA = AU.IDASISTENCIA INNER JOIN asistencia A
	ON AP.IDASISTENCIA = A.IDASISTENCIA WHERE AP.IDPROVEEDOR = ".$XIDPROVEEDOR." and AU.FECHAHORA BETWEEN '$XFECHAINI' AND '$XFECHAFIN'
	union 
	select $XIDPROVEEDOR,'','','','' FROM $catalogo.catalogo_proveedor
	 WHERE $XIDPROVEEDOR NOT IN (SELECT IDPROVEEDOR FROM asistencia_asig_proveedor)  ORDER BY 4 DESC";
	echo $sql_asis_prov;
	$exec_asis_prov = $con->query($sql_asis_prov) ;

	$sql_consulta_tmp="SELECT IDPROVEEDOR,IDASISTENCIA FROM tmp_carga_cde WHERE IDPROVEEDOR=$XIDPROVEEDOR";
//	echo $sql_consulta_tmp;
	$exec_consulta_tmp=$con->query($sql_consulta_tmp);
	while($rset_consulta_tmp = $exec_consulta_tmp->fetch_object())
	{
		$XTMPIDPROVEEDOR=$rset_consulta_tmp->IDPROVEEDOR;
		$XTMPIDASISTENCIA=$rset_consulta_tmp->IDASISTENCIA;


$sql_asis_def="select 
COUNT(CASE(IF(D.IMPORTANCIA='LEVE' AND A.LOCALFORANEO = 'L','TRUE','FALSE')) WHEN 'TRUE' THEN ED.CVEDEFICIENCIA END) LOCALLEVE,
COUNT(CASE(IF(D.IMPORTANCIA='GRAVE' AND A.LOCALFORANEO = 'L','TRUE','FALSE')) WHEN 'TRUE' THEN ED.CVEDEFICIENCIA END) LOCALGRAVE,
COUNT(CASE(IF(D.IMPORTANCIA='LEVE' AND A.LOCALFORANEO = 'F','TRUE','FALSE')) WHEN 'TRUE' THEN ED.CVEDEFICIENCIA END) FORANEOLEVE,
COUNT(CASE(IF(D.IMPORTANCIA='GRAVE' AND A.LOCALFORANEO = 'F','TRUE','FALSE')) WHEN 'TRUE' THEN ED.CVEDEFICIENCIA END) FORANEOGRAVE
 FROM $temporal.expediente_deficiencia ED
 INNER JOIN $catalogo.catalogo_deficiencia D ON ED.CVEDEFICIENCIA = D.CVEDEFICIENCIA
INNER JOIN $temporal.asistencia A ON ED.IDASISTENCIA = A.IDASISTENCIA 
where ED.IDASISTENCIA = ".$XTMPIDASISTENCIA." AND ORIGEN='EXTERNO' AND ED.IDPROVEEDOR=".$XTMPIDPROVEEDOR." GROUP BY A.LOCALFORANEO";
		//echo $sql_asis_def;
		$exec_asis_def = $con->query($sql_asis_def);
		if($rset_asis_def=$exec_asis_def->fetch_object())
		{
			$XDEFLEVELOCAL= $rset_asis_def->LOCALLEVE;
			$XDEFGRAVELOCAL = $rset_asis_def->LOCALGRAVE;
			$XDEFLEVEFORANEO= $rset_asis_def->FORANEOLEVE;
			$XDEFGRAVEFORANEO = $rset_asis_def->FORANEOGRAVE;
			$sql_update_def = "UPDATE tmp_carga_cde SET DEFLEVELOCAL=$XDEFLEVELOCAL,DEFGRAVELOCAL=$XDEFGRAVELOCAL,
			DEFLEVEFORANEO=$XDEFLEVEFORANEO,DEFGRAVEFORANEO=$XDEFGRAVEFORANEO WHERE IDPROVEEDOR = $XTMPIDPROVEEDOR
			 AND IDASISTENCIA = $XTMPIDASISTENCIA";
			//echo $sql_update_def;
			$exec_update_def = $con->query($sql_update_def);
			
		}		
		
		
	}

}


if($idproveedor==0){

$sql_servicio = "SELECT * FROM $catalogo.catalogo_servicio";
$exec_servicio = mysql_query($sql_servicio);

while($rset_servicio = $exec_servicio($exec_servicio))
{
$XIDSERVICIO = $rset_servicio->IDSERVICIO;
$sql_cde = " INSERT INTO proceso_carga_cde_mensual(IDSERVICIO,TOTALEVALUADO,IDPROVEEDOR,LEVELOCAL,LEVEFORANEO,GRAVELOCAL,
GRAVEFORANEO,DEFLEVES,DEFGRAVE,PORLEVE,PORGRAVE,CDE,IDENTIFICADOR,FECHAHORA)
SELECT IDSERVICIO,COUNT(IDASISTENCIA) TOTALEVALUADOS,P.IDPROVEEDOR,
(SELECT COUNT(DEFLEVELOCAL) FROM tmp_carga_cde WHERE DEFLEVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) LEVELOCAL,
(SELECT COUNT(DEFLEVEFORANEO) FROM tmp_carga_cde WHERE DEFLEVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) LEVEFORANEO,
(SELECT COUNT(DEFGRAVELOCAL) FROM tmp_carga_cde WHERE DEFGRAVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) GRAVELOCAL,
(SELECT COUNT(DEFGRAVEFORANEO) FROM tmp_carga_cde WHERE DEFGRAVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) GRAVEFORANEO,
IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0) AS TOTALLEVES,
IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0) AS TOTALGRAVE,
(IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100 AS PORLEVE,
(IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100 AS PORGRAVE,
IF((100-(((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*$PONLEVE)+
((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*$PONGRAVE)))>0,
(100-(((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*$PONLEVE)
+((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*$PONGRAVE))),0) AS CDE,'A','$fecha'
FROM tmp_carga_cde P
WHERE P.IDSERVICIO = '$XIDSERVICIO'
GROUP BY P.IDPROVEEDOR";
//echo $sql_cde;
$exec_cde = $con->query($sql_cde);

}

$sql_insert_prov = "insert into proceso_carga_cde_mensual(IDPROVEEDOR,IDENTIFICADOR) 
select IDPROVEEDOR,'A' FROM $catalogo.catalogo_proveedor where IDPROVEEDOR NOT IN (SELECT DISTINCT IDPROVEEDOR FROM proceso_carga_cde_mensual)";
$exec_insert_prov = $con->query($sql_insert_prov);


$sql_cde_proveedor_mensual=" insert INTO proceso_carga_cde_mensual(TOTALEVALUADO,IDPROVEEDOR,LEVELOCAL,LEVEFORANEO,GRAVELOCAL,GRAVEFORANEO,DEFLEVES,DEFGRAVE,PORLEVE,PORGRAVE,CDE,IDENTIFICADOR)
  SELECT IF(IDASISTENCIA=0,0,COUNT(IDASISTENCIA)) TOTALEVALUADOS,P.IDPROVEEDOR,
 (SELECT COUNT(DEFLEVELOCAL) FROM tmp_carga_cde WHERE DEFLEVELOCAL <> 0 AND IDPROVEEDOR=P.IDPROVEEDOR) LEVELOCAL, 
(SELECT COUNT(DEFLEVEFORANEO) FROM tmp_carga_cde WHERE DEFLEVEFORANEO <> 0  AND IDPROVEEDOR=P.IDPROVEEDOR) LEVEFORANEO, 
(SELECT COUNT(DEFGRAVELOCAL) FROM tmp_carga_cde WHERE DEFGRAVELOCAL <> 0   AND IDPROVEEDOR=P.IDPROVEEDOR) GRAVELOCAL,
 (SELECT COUNT(DEFGRAVEFORANEO) FROM tmp_carga_cde WHERE DEFGRAVEFORANEO <> 0  AND IDPROVEEDOR=P.IDPROVEEDOR) GRAVEFORANEO, 
IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
 WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0  AND IDPROVEEDOR = P.IDPROVEEDOR),0) AS TOTALLEVES, 
IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
 WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0  AND IDPROVEEDOR = P.IDPROVEEDOR),0) AS TOTALGRAVE, 
(IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM 
tmp_carga_cde WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0  AND IDPROVEEDOR = P.IDPROVEEDOR),0)/
 COUNT(IDASISTENCIA)))*100 AS PORLEVE, (IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,
(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '1' AND
 IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100 AS PORGRAVE, IF((100-(((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,
(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '1' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/
 COUNT(IDASISTENCIA)))*100*0.5)+ ((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA)
 FROM tmp_carga_cde WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '1' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/
 COUNT(IDASISTENCIA)))*100*1.5)))>0, (100-(((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM
 tmp_carga_cde WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND  IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*0.5)
 +((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde WHERE
 DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '1' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*1.5))),0) AS CDE,
'P' FROM tmp_carga_cde P  GROUP BY P.IDPROVEEDOR";
$exec_cde_proveedor_mensual=$con->query($sql_cde_proveedor_mensual);

}
else
{

$sql_servicio = "SELECT * FROM $catalogo.catalogo_servicio";
$exec_servicio = $con->query($sql_servicio);

while($rset_servicio = $exec_servicio->fetch_object())
{

$XIDSERVICIO = $rset_servicio->IDSERVICIO;

$sql_consulta_cde = " 
SELECT IDSERVICIO,COUNT(IDASISTENCIA) TOTALEVALUADOS,P.IDPROVEEDOR,
(SELECT COUNT(DEFLEVELOCAL) FROM tmp_carga_cde WHERE DEFLEVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) LEVELOCAL,
(SELECT COUNT(DEFLEVEFORANEO) FROM tmp_carga_cde WHERE DEFLEVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) LEVEFORANEO,
(SELECT COUNT(DEFGRAVELOCAL) FROM tmp_carga_cde WHERE DEFGRAVELOCAL <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) GRAVELOCAL,
(SELECT COUNT(DEFGRAVEFORANEO) FROM tmp_carga_cde WHERE DEFGRAVEFORANEO <> 0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR=P.IDPROVEEDOR) GRAVEFORANEO,
IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0) AS TOTALLEVES,
IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0) AS TOTALGRAVE,
(IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100 AS PORLEVE,
(IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100 AS PORGRAVE,
IF((100-(((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*$PONLEVE)+
((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*$PONGRAVE)))>0,
(100-(((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*$PONLEVE)
+((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '$XIDSERVICIO' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*$PONGRAVE))),0) AS CDE,'A','$fecha'
FROM tmp_carga_cde P
WHERE P.IDSERVICIO = '$XIDSERVICIO' and P.IDPROVEEDOR = $idproveedor
GROUP BY P.IDPROVEEDOR";
echo $sql_consulta_cde;

$exec_consulta_cde = $con->query($sql_consulta_cde);

        while($rset_consulta_cde=$exec_consulta_cde->fetch_object()){
                $XIDSERVICIO = $rset_consulta_cde->IDSERVICIO;
                $XTOTALEVALUADOS = $rset_consulta_cde->TOTALEVALUADOS;
                $XIDPROVEEDOR = $rset_consulta_cde->IDPROVEEDOR;
                $XLEVELOCAL = $rset_consulta_cde->LEVELOCAL;
                $XLEVEFORANEO = $rset_consulta_cde->LEVEFORANEO;
                $XGRAVELOCAL = $rset_consulta_cde->GRAVELOCAL;
                $XGRAVEFORANEO = $rset_consulta_cde->GRAVEFORANEO;
                $XTOTALLEVE = $rset_consulta_cde->TOTALLEVE;
                $XTOTALGRAVE = $rset_consulta_cde->TOTALGRAVE;
                $XPORLEVE = $rset_consulta_cde->PORLEVE;
                $XPORGRAVE = $rset_consulta_cde->PORGRAVE;
                $XCDE = $rset_consulta_cde->CDE;

                $sql_cde = "UPDATE proceso_carga_cde_mensual SET TOTALEVALUADOS = $XTOTALEVALUADOS,LEVELOCAL=$XLEVELOCAL,LEVEFORANEO=$XLEVEFORANEO,
                GRAVELOCAL=$XGRAVELOCAL,GRAVEFORANEO=$XGRAVEFORANEO,TOTALLEVE=$XTOTALLEVE,TOTALGRAVE=$XTOTALGRAVE,PORLEVE=$XPORLEVE=PORGRAVE=$XPORGRAVE,CDE=$XCDE
                WHERE IDSERVICIO=$XIDSERVICIO AND   IDPROVEEDOR=$idproveedor AND FECHAHORA = $fecha AND IDENTIFICADOR = 'A'";
                echo $sql_cde;
                $exec_cde = $con->query($sql_cde);

        }

$sql_proveedor_cde_mensual=" SELECT IF(IDASISTENCIA=0,0,COUNT(IDASISTENCIA)) TOTALEVALUADOS,P.IDPROVEEDOR,
 (SELECT COUNT(DEFLEVELOCAL) FROM tmp_carga_cde WHERE DEFLEVELOCAL <> 0 AND IDPROVEEDOR=P.IDPROVEEDOR) LEVELOCAL,
(SELECT COUNT(DEFLEVEFORANEO) FROM tmp_carga_cde WHERE DEFLEVEFORANEO <> 0  AND IDPROVEEDOR=P.IDPROVEEDOR) LEVEFORANEO,
(SELECT COUNT(DEFGRAVELOCAL) FROM tmp_carga_cde WHERE DEFGRAVELOCAL <> 0   AND IDPROVEEDOR=P.IDPROVEEDOR) GRAVELOCAL,
 (SELECT COUNT(DEFGRAVEFORANEO) FROM tmp_carga_cde WHERE DEFGRAVEFORANEO <> 0  AND IDPROVEEDOR=P.IDPROVEEDOR) GRAVEFORANEO,
IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
 WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0  AND IDPROVEEDOR = P.IDPROVEEDOR),0) AS TOTALLEVES,
IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde
 WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0  AND IDPROVEEDOR = P.IDPROVEEDOR),0) AS TOTALGRAVE,
(IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM
tmp_carga_cde WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0  AND IDPROVEEDOR = P.IDPROVEEDOR),0)/
 COUNT(IDASISTENCIA)))*100 AS PORLEVE, (IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,
(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '1' AND
 IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100 AS PORGRAVE, IF((100-(((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,
(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND IDSERVICIO = '1' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/
 COUNT(IDASISTENCIA)))*100*0.5)+ ((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA)
 FROM tmp_carga_cde WHERE DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '1' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/
 COUNT(IDASISTENCIA)))*100*1.5)))>0, (100-(((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFLEVELOCAL+DEFLEVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM
 tmp_carga_cde WHERE DEFLEVELOCAL+DEFLEVEFORANEO<>0 AND  IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*0.5)
 +((IF(COUNT(IDASISTENCIA)=0,0,IF((DEFGRAVELOCAL+DEFGRAVEFORANEO)<>0,(SELECT COUNT(IDASISTENCIA) FROM tmp_carga_cde WHERE
 DEFGRAVELOCAL+DEFGRAVEFORANEO<>0 AND IDSERVICIO = '1' AND IDPROVEEDOR = P.IDPROVEEDOR),0)/ COUNT(IDASISTENCIA)))*100*1.5))),0) AS CDE,
'P' FROM tmp_carga_cde P  GROUP BY P.IDPROVEEDOR";

$exec_proveedor_cde_mensual=$con->query($sql_cde_proveedor_mensual);
	while($rset_consulta_cde_p=$exec_proveedor_cde_mensual->fetch_object()){
                $XPTOTALEVALUADOS = $rset_consulta_cde_p->TOTALEVALUADOS;
                $XPIDPROVEEDOR = $rset_consulta_cde_p->IDPROVEEDOR;
                $XPLEVELOCAL = $rset_consulta_cde_p->LEVELOCAL;
                $XPLEVEFORANEO = $rset_consulta_cde_p->LEVEFORANEO;
                $XPGRAVELOCAL = $rset_consulta_cde_p->GRAVELOCAL;
                $XPGRAVEFORANEO = $rset_consulta_cde_p->GRAVEFORANEO;
                $XPTOTALLEVE = $rset_consulta_cde_p->TOTALLEVE;
                $XPTOTALGRAVE = $rset_consulta_cde_p->TOTALGRAVE;
                $XPPORLEVE = $rset_consulta_cde_p->PORLEVE;
                $XPPORGRAVE = $rset_consulta_cde_p->PORGRAVE;
                $XPCDE = $rset_consulta_cde_p->CDE;

	
               $sql_cde_prov = "UPDATE $temporal.proceso_carga_cde_mensual SET TOTALEVALUADOS = $XTOTALEVALUADOS,LEVELOCAL=$XLEVELOCAL,LEVEFORANEO=$XLEVEFORANEO,
                GRAVELOCAL=$XGRAVELOCAL,GRAVEFORANEO=$XGRAVEFORANEO,TOTALLEVE=$XTOTALLEVE,TOTALGRAVE=$XTOTALGRAVE,PORLEVE=$XPORLEVE=PORGRAVE=$XPORGRAVE,CDE=$XCDE
                WHERE IDSERVICIO=$XIDSERVICIO AND   IDPROVEEDOR=$idproveedor AND FECHAHORA = $fecha AND IDENTIFICADOR = 'P'";
                echo $sql_cde_prov;
                $exec_cde = $con->query($sql_cde_prov);

	}
   }
}


$sql_drop_tmp = "drop table $temporal.$tabla";
$exec_drop_tmp = $con->query($sql_drop_tmp);

?>
