<style type="text/css" media="screen">
body, html {margin:0;padding:0;font-family: Tahoma, sans-serif;font-size: 16px;color: #000;}			
a:link, a:active, a:visited 
	{
	color: #FF6600;
	}
a:hover 
	{
	color: #FFFFCC;
	}
ul#dock 
	{
	border: 2px solid #999;
	background: #ccc;
	height: auto!important;
	padding: 0 12px 0 12px;
	position: absolute;
	left:50%;
	background:#ccc;
	bottom: 0;
	}
ul#dock li
 	{
	display: inline;
	position: relative;
	margin-bottom: 0;
	float: left;
	background:#ccc;
 	}
ul#dock * 
	{
 	margin-bottom: 0;
	}
ul#dock li a 
	{
	display: block;
	position: relative;
	height:54px;
	height:54px;
	}
ul#dock li a img
	{
	display: block;
	height:100%;
	width:100%;
	position: relative;
	border:0;
	}
.clear {clear:both}
</style>

<ul id="dock">
		<li><a style="width:54px" href="#" title="Finder"><img src="/imagenes/prueba/finder.png" alt="Finder"></a></li>
		<li><a style="width:54px" href="#" title="System Preferences"><img src="/imagenes/prueba/sysprefs.png" alt="System Preferences"></a></li>
</ul>
<div class="clear"></div>